upstream_project_url: https://github.com/stratis-storage/libcryptsetup-rs

packages:
  libcryptsetup-rs-sys:
    specfile_path: ../distro/rust-libcryptsetup-rs-sys.spec
    downstream_package_name: rust-libcryptsetup-rs-sys
    actions:
      post-upstream-clone:
        - "mkdir ../distro"
        - "bash -c '(cd ../distro; wget https://src.fedoraproject.org/rpms/rust-libcryptsetup-rs-sys/raw/rawhide/f/rust-libcryptsetup-rs-sys.spec https://src.fedoraproject.org/rpms/rust-libcryptsetup-rs-sys/raw/rawhide/f/rust2rpm.toml)'"
        - "cargo install cargo-get"
      create-archive:
        - "bash -c '(cd libcryptsetup-rs-sys; cargo package --no-verify)'"
        - "bash -c '(cd ../distro; rust2rpm libcryptsetup-rs-sys)'"
        - "bash -c 'echo \"libcryptsetup-rs-sys/target/package/libcryptsetup-rs-sys-$(cd libcryptsetup-rs-sys; cargo get package.version).crate\"'"
      get-current-version:
        - "bash -c '(cd libcryptsetup-rs-sys; cargo get package.version)'"

  libcryptsetup-rs:
    specfile_path: ../distro/rust-libcryptsetup-rs.spec
    downstream_package_name: rust-libcryptsetup-rs
    actions:
      post-upstream-clone:
        - "mkdir ../distro"
        - "bash -c '(cd ../distro; wget https://src.fedoraproject.org/rpms/rust-libcryptsetup-rs/raw/rawhide/f/rust-libcryptsetup-rs.spec)'"
        - "cargo install cargo-get"
      create-archive:
        - "cargo package --no-verify"
        - "bash -c '(cd ../distro; rust2rpm libcryptsetup-rs)'"
        - "bash -c 'echo \"target/package/libcryptsetup-rs-$(cargo get package.version).crate\"'"
      get-current-version:
        - "cargo get package.version"

srpm_build_deps:
  - cargo
  - rust2rpm
  - rust2rpm-helper
  - wget2
  - wget2-wget

jobs:
  - job: copr_build
    trigger: pull_request
    identifier: copr_pull
    targets:
      - fedora-all

  - job: copr_build
    trigger: commit
    identifier: copr_commit
    targets:
      - fedora-all

notifications:
  pull_request:
    successful_build: true
