---
name: libcryptsetup CI

on:
  push:
    branches: [master]
    paths-ignore:
      - 'CHANGES.txt'
      - '**/README.md'
  pull_request:
    branches: [master]
    paths-ignore:
      - 'CHANGES.txt'
      - '**/README.md'

  workflow_dispatch:

jobs:
  # MANDATORY CHECKS USING CURRENT DEVELOPMENT TOOLCHAIN:
  format:
    env:
      TASK: fmt-ci
    runs-on: ubuntu-22.04
    steps:
      - name: Install git
        run: sudo apt-get install git
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Test format on CURRENT DEVELOPMENT RUST TOOLCHAIN
        run: make -f Makefile $TASK
  lint:
    env:
      TASK: clippy
    runs-on: ubuntu-22.04
    steps:
      - name: Install git
        run: sudo apt-get install git
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - name: Install dependencies
        run: >
          sudo apt-get install libcryptsetup-dev
      - name: Test linting on CURRENT DEVELOPMENT RUST TOOLCHAIN
        run: make -f Makefile $TASK

  stable:
    strategy:
      matrix:
        include:
          - task: make -f Makefile build
            dependencies: libcryptsetup-dev
          - task: make -f Makefile build-examples
            dependencies: libcryptsetup-dev
          - task: make -f Makefile docs-ci
            dependencies: libcryptsetup-dev
          - task: make -f Makefile test
            dependencies: libcryptsetup-dev libkeyutils-dev
          - task: make -f Makefile test-mutex
            dependencies: libcryptsetup-dev libkeyutils-dev
          - task: make -f Makefile test-mutex-guard
            dependencies: libcryptsetup-dev libkeyutils-dev
          - task: make -f Makefile release
            dependencies: libcryptsetup-dev
    runs-on: ubuntu-22.04
    steps:
      - name: Install git
        run: sudo apt-get install git
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install dependencies
        run: >
          sudo apt-get install ${{ matrix.dependencies }}
      - name: Test ${{ matrix.task }} on CURRENT DEVELOPMENT RUST TOOLCHAIN
        run: ${{ matrix.task }}

  lowest_supported:
    strategy:
      matrix:
        include:
          - task: make -f Makefile test
            dependencies: libcryptsetup-dev libkeyutils-dev
          - task: make -f Makefile test-mutex
            dependencies: libcryptsetup-dev libkeyutils-dev
          - task: make -f Makefile test-mutex-guard
            dependencies: libcryptsetup-dev libkeyutils-dev
    runs-on: ubuntu-22.04
    steps:
      - name: Install git
        run: sudo apt-get install git jq
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install dependencies
        run: sudo apt-get install ${{ matrix.dependencies }}
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Set toolchain to MSRV
        uses: stratis-storage/github-actions/set-rust-toolchain@HEAD
      - name: Test ${{ matrix.task }} on LOWEST SUPPORTED RUST TOOLCHAIN
        run: ${{ matrix.task }}

  # MANDATORY TESTING ON FEDORA
  fedora:
    strategy:
      matrix:
        include:
          # Fedora 33
          - task: make -f Makefile build
            dependencies: cryptsetup-devel
            container: 33
          - task: make -f Makefile build-examples
            dependencies: cryptsetup-devel
            container: 33
          - task: make -f Makefile docs-ci
            dependencies: cryptsetup-devel
            container: 33
          - task: make -f Makefile test
            dependencies: cryptsetup-devel keyutils-libs-devel
            container: 33
          - task: make -f Makefile test-mutex
            dependencies: cryptsetup-devel keyutils-libs-devel
            container: 33
          - task: make -f Makefile test-mutex-guard
            dependencies: cryptsetup-devel keyutils-libs-devel
            container: 33
          - task: make -f Makefile test-loopback
            dependencies: cryptsetup-devel keyutils-libs-devel
            container: 33
          - task: make -f Makefile release
            dependencies: cryptsetup-devel
            container: 33

          # Fedora 34
          - task: make -f Makefile build
            dependencies: cryptsetup-devel
            container: 34
          - task: make -f Makefile build-examples
            dependencies: cryptsetup-devel
            container: 34
          - task: make -f Makefile docs-ci
            dependencies: cryptsetup-devel
            container: 34
          - task: make -f Makefile test
            dependencies: cryptsetup-devel keyutils-libs-devel
            container: 34
          - task: make -f Makefile test-mutex
            dependencies: cryptsetup-devel keyutils-libs-devel
            container: 34
          - task: make -f Makefile test-mutex-guard
            dependencies: cryptsetup-devel keyutils-libs-devel
            container: 34
          - task: make -f Makefile test-loopback
            dependencies: cryptsetup-devel keyutils-libs-devel
            container: 34
          - task: make -f Makefile release
            dependencies: cryptsetup-devel
            container: 34

          # Fedora 38
          - task: make -f Makefile build
            dependencies: cryptsetup-devel
            container: 38
          - task: make -f Makefile build-examples
            dependencies: cryptsetup-devel
            container: 38
          - task: make -f Makefile docs-ci
            dependencies: cryptsetup-devel
            container: 38
          - task: make -f Makefile test
            dependencies: cryptsetup-devel keyutils-libs-devel
            container: 38
          - task: make -f Makefile test-mutex
            dependencies: cryptsetup-devel keyutils-libs-devel
            container: 38
          - task: make -f Makefile test-mutex-guard
            dependencies: cryptsetup-devel keyutils-libs-devel
            container: 38
          - task: make -f Makefile test-loopback
            dependencies: cryptsetup-devel keyutils-libs-devel
            container: 38
          - task: make -f Makefile release
            dependencies: cryptsetup-devel
            container: 38

    runs-on: ubuntu-22.04
    container:
      image: fedora:${{ matrix.container }}
      options: --privileged -v /dev:/dev
    steps:
      - name: Install git
        run: dnf install -y git jq
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install dependencies
        run: dnf install -y make gcc clang-devel ${{ matrix.dependencies }}
      - name: Set toolchain to MSRV
        uses: stratis-storage/github-actions/set-rust-toolchain@HEAD
      - name: Test ${{ matrix.task }} on LOWEST SUPPORTED RUST TOOLCHAIN
        run: ${{ matrix.task }}

  general_checks:
    uses: stratis-storage/github-actions/.github/workflows/reusable_general.yml@master
    with:
      fedora-container-image-number: 44  # CURRENT DEVELOPMENT ENVIRONMENT
